---
- name: Configure Lab Instances
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Add deadsnakes PPA for Python 3.10
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
      become: yes

    - name: Install Python 3.10 and venv
      apt:
        name:
          - python3.10
          - python3.10-venv
        state: present
        update_cache: yes
      become: yes

    - name: Create a dedicated virtual environment for Python 3.10
      ansible.builtin.command: python3.10 -m venv /opt/python3.10-venv
      args:
        creates: /opt/python3.10-venv/bin/activate
      become: yes

    - name: Upgrade pip inside the virtual environment
      ansible.builtin.command: /opt/python3.10-venv/bin/python -m pip install --upgrade pip
      become: yes

    - name: Add venv bin directory to system-wide profile (optional)
      ansible.builtin.lineinfile:
        path: /etc/profile.d/python3.10-venv.sh
        line: 'export PATH="/opt/python3.10-venv/bin:$PATH"'
        create: yes
      become: yes
