---
- name: Configure Lab Instances
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install Python 3.10 and pip
      ansible.builtin.apt:
        name:
          - python3.10
          - python3-pip
        state: present
